version: "3.8"

services:
  db:
    image: mariadb
    container_name: mariadb
    env_file:
      - .env.mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - back-db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    env_file:
      - .env.phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    networks:
      - back-db

  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: express_server
    env_file:
      - .env.back
    ports:
      - "8080:8080"
    depends_on:
      - db
    command:
      # ["dockerize", "-wait", "tcp://db:3306", "-timeout", "60s", "npm", "start"]
      ["npm", "start"]
    networks:
      - back-db
      - front-back
      - back-python

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_app
    env_file:
      - .env.front
    ports:
      - "80:80"
    depends_on:
      - back
    networks:
      - front-back

  python:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: python_server
    env_file:
      - .env.python
    ports:
      - "5000:5000"
    networks:
      - back-python

  portainer:
    image: portainer/portainer-ce
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always

volumes:
  portainer_data:
  mariadb_data:

networks:
  back-db:
  front-back:
  back-python:
